# Generated by Django 2.1.5 on 2019-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('otchestvo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспортные данные')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
            ],
        ),
    ]
