# Generated by Django 2.1.5 on 2019-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ сессии'),
        ),
    ]
