# Generated by Django 2.1.5 on 2019-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_guest_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта'),
        ),
    ]
