# Generated by Django 2.1.5 on 2019-01-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190116_2117'),
        ('customuser', '0004_auto_20190115_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='used_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.PromoCode', verbose_name='Использованный промо-код при текущей корзине'),
        ),
        migrations.AddField(
            model_name='user',
            name='used_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.PromoCode', verbose_name='Использованный промо-код при текущей корзине'),
        ),
    ]
