# Generated by Django 2.1.5 on 2019-01-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_auto_20190116_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allow_email',
            field=models.BooleanField(default=True, verbose_name='Согласен на рассылку'),
        ),
    ]
