# Generated by Django 2.1.5 on 2019-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_user_is_allow_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_ok',
            field=models.BooleanField(default=False),
        ),
    ]
