# Generated by Django 2.1.5 on 2019-01-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='f_id',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 18, 12, 48, 214385), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
