# Generated by Django 2.1.5 on 2019-01-13 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190113_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(default='Не указано', max_length=5, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.CharField(default='Не указано', max_length=5, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(default='Не указано', max_length=5, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(default='Не указано', max_length=5, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 18, 38, 6, 733873), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
