# Generated by Django 2.1.5 on 2019-01-13 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190113_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Краткое описание для главной'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 22, 23, 24, 614620), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
