# Generated by Django 2.1.5 on 2019-01-14 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20190113_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 15, 48, 4, 587496), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
