# Generated by Django 2.1.5 on 2019-01-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190114_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 16, 7, 51, 899250), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
