# Generated by Django 2.1.5 on 2019-01-14 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190114_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 22, 2, 0, 819673), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
