# Generated by Django 2.1.5 on 2019-01-15 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20190114_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 10, 29, 13, 626453), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
