# Generated by Django 2.1.5 on 2019-01-21 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190116_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 22, 2, 45, 431291), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
