# Generated by Django 2.1.5 on 2019-01-21 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20190121_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 23, 33, 17, 811014), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
