# Generated by Django 2.1.5 on 2019-01-28 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20190127_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 20, 54, 22, 698136), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
