# Generated by Django 2.1.5 on 2019-01-28 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20190128_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 23, 8, 27, 937967), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
