# Generated by Django 2.1.5 on 2019-01-30 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20190128_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 9, 48, 46, 341769), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
