# Generated by Django 2.1.5 on 2019-01-30 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20190130_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 20, 37, 45, 485177), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
