# Generated by Django 2.1.5 on 2019-01-31 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20190130_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ManyToManyField(blank=True, db_index=True, to='item.Collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Скидка %'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать товар ?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Товар новинка ?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_present',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Товар в наличии ?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 19, 28, 49, 138468), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
