# Generated by Django 2.1.5 on 2019-02-03 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_auto_20190131_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Изображение для товара', 'verbose_name_plural': 'Изображения для товара'},
        ),
        migrations.AddField(
            model_name='item',
            name='name_lower',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 21, 45, 42, 573730), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
