# Generated by Django 2.1.5 on 2019-01-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190114_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзинах'},
        ),
    ]
