# Generated by Django 2.1.5 on 2019-01-28 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вариант оплаты заказа')),
            ],
            options={
                'verbose_name': 'Вариант оплаты заказа',
                'verbose_name_plural': 'Варианты оплаты заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вариант доставки заказа')),
            ],
            options={
                'verbose_name': 'Вариант доставки заказа',
                'verbose_name_plural': 'Варианты доставки заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_with_code',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость заказа с учетом промо-кода'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderPayment', verbose_name='Оплата заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderShipping', verbose_name='Доставка заказа'),
        ),
    ]
