# Generated by Django 2.1.5 on 2019-01-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190128_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='В заказе'),
        ),
    ]
