# Generated by Django 2.1.5 on 2019-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190130_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трек код'),
        ),
    ]
